version: '3'

services:
    mysql:
        image: mysql:8.0.26
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql_plg
        restart: always
        ports:
            - '3307:3306'
        volumes:
            - ./bd:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 32130
            MYSQL_DATABASE_1: plg_log
            MYSQL_DATABASE_2: plg_log_adm
            MYSQL_USER: adm_plg
            MYSQL_PASSWORD: adm123

    php:
        build: .
        container_name: php_plg
        image: php:8.0.19
        restart: always
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - .:/var/www/html
        ports:
            - '8080:80'
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_plg
        ports:
            - '8081:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3307
            PMA_USER: adm_plg
            PMA_PASSWORD: adm123
            PMA_ARBITRARY: 1
        depends_on:
            - mysql
    
    python:
        build: .
        container_name: python_plg
        restart: always
        volumes:
            - .:/app