version: '3'

services:
    mysql:
        image: mysql:8.0.26
        container_name: mysql_plg
        restart: always
        ports:
            - '3307:3306'
        volumes:
            - ./bd:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 32130
            MYSQL_DATABASE_1: plg_log
            MYSQL_DATABASE_2: plg_log_adm
            MYSQL_USER: adm_plg
            MYSQL_PASSWORD: adm123
        networks:
            - plglog

    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        container_name: php_plg
        image: php:8.0-apache
        restart: always
        environment:
            - TZ=America/Sao_Paulo
        volumes:
            - .:/var/www/html
        ports:
            - '8085:80'
        links:
            - mysql
        networks:
            - plglog

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_plg
        ports:
            - '8086:80'
        environment:
            PMA_HOST: mysql_plg  # Alterado para o nome do container do MySQL
            PMA_PORT: 3306       # A porta padrão do MySQL é 3306
            PMA_ARBITRARY: 1
        networks:
            - plglog
        depends_on:
            - mysql
networks:
    plglog: